[platformio]
description = open sores audio player

[env]
extra_scripts = 
    pre:delete-generated-files.py
    pre:git-version.py
    pre:difm-to-presets.py 
    pre:generate-build-date.py
    pre:icon-inline.py
    pre:inject-version-info.py
    pre:gzip-html-files.py

board_build.embed_files =
    src/generated/index.html.gz

lib_deps =
    https://github.com/baldram/ESP_VS1053_Library#25b4725c872938e69cf6e165a7a7538a8348a399
    https://github.com/CelliesProjects/ESP32_VS1053_Stream#6d36bb481127b818c41534706500e9e7ecefd63a
    https://github.com/hoeken/PsychicHttp#418a3285290aa13a0e2941f58b571453d6701d17
    https://github.com/adafruit/Adafruit-GFX-Library#ac6d7c3869a693d406f77b9bfcd486b0673169f0
    https://github.com/adafruit/Adafruit_SSD1306#d94f699451d72286357cba7259055ffff2c2940b

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ;-D CORE_DEBUG_LEVEL=3
    ;ESP_LOG_NONE,       0
    ;ESP_LOG_ERROR,      1
    ;ESP_LOG_WARN,       2
    ;ESP_LOG_INFO,       3
    ;ESP_LOG_DEBUG,      4
    ;ESP_LOG_VERBOSE     5

check_tool = cppcheck
check_flags = --enable=all
lib_ldf_mode = chain+


[env:develop]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = lolin_s3_mini
framework = arduino

board_build.partitions = huge_app.csv

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=3


[env:release]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = lolin_s3_mini
framework = arduino

board_build.partitions = huge_app.csv

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    ${env.build_flags}
    -D CORE_DEBUG_LEVEL=0
